[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "video_human_detection"
version = "1.0.0"
requires-python = ">=3.11"

dependencies = [
  "ultralytics",
  "opencv-python"
]
